### ISSUE TITLE
Allow input pad locations to be specified using XDC format

### ISSUE THREAD

**Issue by jgoeders** [SymbiFlow/symbiflow-xc-fasm2bels#20]
It would be nice if you could provide a set of pin constraints from the original bitstream compile, such that when translating fasm to bels, the top-level input names could be mapped back to the original input names.  

This would be similar to the "icebox_vlog.py -P" functionality if you are familiar with the icestorm tools.

I'm assuming this option doesn't already exist?

If you're not already working on this, I would be happy to work on it and upstream it.  If you have any advice on where to look in the code first, it would be much suggested.  Thanks!

**Comment by mithro** [comment]
@litghost / @acomodi -- Any idea if this already works? I assume that @jgoeders is using an existing vivado design and not something produced from VPR which would have this annotation?

**Comment by acomodi** [comment]
I think that what is missing to get the top level IO names are either one of the following options:
- A PCF constraints file
- They synthesized eblif file that contains IO_LOC_PAIRS attributes on IO buffer instances. The IO_LOC_PAIRS are added with a yosys plugin at synthesis time.

I think that adding the PCF constraint file should be the way to go and should solve the problem.

**Comment by jgoeders** [comment]
Ah, ok.  I see there is already a `--pcf` argument.  Not sure how I missed that.  I assume this only takes PCF and not XDC for pin constraints? @mithro, is there a symbiflow tool that converts between these?

**Comment by mithro** [comment]
@jgoeders We are generally moving towards supporting XDC / SDC everywhere (rather than PCF). I don't think this has been done for fasm2bels yet?

**Comment by jgoeders** [comment]
@acomodi If there's no XDC support I can add it and upstream it.

@mithro Is there a standard parser you are using across Symbiflow projects?

**Comment by acomodi** [comment]
@jgoeders Currently there is no direct XDC parser to read the pad locations within fasm2bels, so this could be a good addition IMO to the tool.

**Comment by jgoeders** [comment]
Fixed in #21
