### ISSUE TITLE
Remove capnp files

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/symbiflow-xc-fasm2bels#7]
Remove dependency on capnp schemas and let the external tool using fasm2bels to point to the capnp schema dir.

This relies on https://github.com/SymbiFlow/conda-packages/pull/123 to have the possibility to retrieve the capnp dir stored in the vtr conda package.

**Comment by litghost** [comment]
I believe this issue can be closed?

**Comment by acomodi** [comment]
Yes, this has been solved
