### ISSUE TITLE
env target broken with make-env

### ISSUE THREAD

**Issue by jgoeders** [SymbiFlow/symbiflow-xc-fasm2bels#71]
`make env` runs `git submodule update --init --recursive`, which brings in the *make-env* submodule, but *make-env* is needed *before* the *env* target can be run (since the make-env also uses the env target).

Need a new Makefile target that is run before env?

This isn't picked up by [CI ](https://github.com/SymbiFlow/symbiflow-xc-fasm2bels/blob/4e126da5ef4c357a85129223333ab905f7f9935f/.github/workflows/ci.yml#L24) because it uses the recursive option of actions/checkout@v1.

**Comment by mithro** [comment]
There is a template for what your Makefile should look like at https://github.com/SymbiFlow/make-env/blob/master/Makefile.template

**Comment by jgoeders** [comment]
Thanks.  

Looks like @jaromharris missed [this part](https://github.com/SymbiFlow/make-env/blob/59adb0f248cc4a5d764b6b06224bf6adea7fa36e/Makefile.template#L20) that fixes this issue.  We'll get it fixed.

**Comment by jgoeders** [comment]
OK, that makes sense.  No need to have make-env using conda, plus virtualenv.

**Comment by jgoeders** [comment]
Fixed in #72
